<?php
/**
 * 查看 widget-不同状态查看点击的<a></a>标签链接不同
 */
namespace common\components;

use yii\base\Widget;
use yii\helpers\Html;
use common\models\Picorder;

class PicoperateWidget extends Widget
{
    public $orderid; //订单id
    public $status; //订单状态

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //ob_start(); //要在 begin() 和 end() 函数之间调用显示内容,需要设置(1)
    }

    public function run()
    {
        //$content = ob_get_clean(); //要在 PicoperateWidget::begin() 和 PicoperateWidget::end() 函数之间调用显示内容,$content为begin()和end()内容，需要设置(2)
        $orderIsLock = \Yii::$app->ServiceSupport->isLockOrder($this->orderid, $this->status+1); //检测是否有待修片或待看片的订单在修片中或看片中
        $url = '-';
        switch ($this->status) {
            case Picorder::OS_ORDER_FAILD : //订单失败
                $url = '-';
                break;
            case Picorder::OS_ORDER_READY_PHOTO : //待拍摄
                $url = '-';
                break;
            case Picorder::OS_ORDER_READY_RETOUCH : //待修片
                if ($orderIsLock) {
                    $url = '修片中';
                } else {
                    $url = Html::a('接单修片', ['list/operate-order', 'startStatus'=>$this->status, 'orderid'=>$this->orderid]);
                }
                break;
            case Picorder::OS_ORDER_RETOUCHING : //修片中
                $url = '修片中';
                break;
            case Picorder::OS_ORDER_READY_VIEW : //待看片
                if ($orderIsLock) {
                    $url = '看片中';
                } else {
                    $url = Html::a('接单看片', ['list/operate-order', 'startStatus'=>$this->status, 'orderid'=>$this->orderid]);
                }
                break;
            case Picorder::OS_ORDER_VIEWING : //看片中
                $url = '看片中';
                break;
            case Picorder::OS_ORDER_SUCCESS : //订单成功
                $url = Html::a('查看', []);
                break;
            default:
                $url = '-';
        }
        return $url;
    }
}